config/routes.rb
Rails3MongoidOmniauth::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [ :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  match '/about' => "home#about"
  match '/panel' => "home#panel"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :provider, :uid

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.token = auth['credentials']['token'] || ""
         if auth['credentials']['refresh_token']
         user.secret = auth['credentials']['refresh_token'] || ""
         else
         user.secret = auth['credentials']['token'] || ""
         end
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
    @auth = request.env["omniauth.auth"]
    @user = current_user
  end
  
  def panel
     @user = current_user
     
     if (user_signed_in? )
        client = OAuth2::Client.new(
            "15212955717.apps.googleusercontent.com", "KYISer2Xb_q04lj5zvuAS6bR",
            :site => "https://accounts.google.com",
            :token_url => "/o/oauth2/token",
            :authorize_url => "/o/oauth2/auth")
        access_token = OAuth2::AccessToken.from_hash(client,
            {:refresh_token => current_user.secret})
        access_token = access_token.refresh!
        session = GoogleDrive.login_with_oauth(access_token)

        # First worksheet of
        # https://docs.google.com/spreadsheet/ccc?key=pz7XtlQC-PYx-jrVMJErTcg
        @ws = session.spreadsheet_by_key("0ArJbOFyntyO0dDVxOC1Ka0YyWHlRcGtSalBTUXNKb3c").worksheets[0]

         end
     
  end
  
  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => "Signed in via #{auth['provider']}!" 
    end

  end

  def destroy
    session[:user_id] = nil 
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?

  def index
    @users = User.paginate(:page => params[:page])
  end

    def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => 'Profile updated!'
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
    redirect_to edit_user_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h3>Welcome to Capital Tweet</h3>
<p>Capital Tweet allows you to link your Buffer account to a Google Spreadsheet, queue up entries in that spreadsheet, and ensure that your Buffer queue stays full in the event that you do not have time to make manual entries.  Login for both services is performed via OAuth.  Enjoy!</p>
<br />
<br />

app/views/home/index.html.erb
<h3>Welcome to Capital Tweet</h3>

<p>Capital Tweet allows you to link your Buffer account to a Google Spreadsheet, queue up entries in that spreadsheet, and ensure that your Buffer queue stays full in the event that you do not have time to make manual entries.  Login for both services is performed via OAuth.  Enjoy!</p>
<br />
<br />
<p>Current users on system:</p>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, edit_user_path(user) %></p>
<% end %>

app/views/home/panel.html.erb
<h3>Welcome to Capital Tweet</h3>
<p>Capital Tweet allows you to link your Buffer account to a Google Spreadsheet, queue up entries in that spreadsheet, and ensure that your Buffer queue stays full in the event that you do not have time to make manual entries.  Login for both services is performed via OAuth.  Enjoy!</p>
<br />
<br />
<% if (user_signed_in? ) %>
<h3>Tweets listing of <strong><%= @ws.title%></strong> Google Spreadsheet</h3>Located at <a href="https://docs.google.com/spreadsheet/ccc?key=0ArJbOFyntyO0dDVxOC1Ka0YyWHlRcGtSalBTUXNKb3c">this link</a>.

<% for $i in 3..7 %>
<p><%=@ws["A"+$i.to_s] %> - Date: <%=@ws["B"+$i.to_s] %> - Length[<%= @ws["C"+$i.to_s]%>]</p>
<% end %>
<% else %>
<p>Please sign in to view Spreadsheet Tweets.</p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Capital Tweet", root_path, :class => 'brand' %>
<ul class="nav">
	<li class="<%= 'active' if params[:action] == 'index' %>"> <%= link_to 'Home', root_path %> </li>
	<li class="<%= 'active' if params[:action] == 'about' %>"> <%= link_to 'About', about_path %> </li>
    <li class="<%= 'active' if params[:action] == 'panel' %>"> <%= link_to 'Buffer Your Google!', panel_path %> </li>
</ul>
<% if user_signed_in? %>
<div class="btn-group pull-right">
	<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	              <i class="icon-user"></i> <%= current_user.name %>
	              <span class="caret"></span>
	            </a>
				<ul class="dropdown-menu">
				              <li><%=link_to "Edit Profile", edit_user_path(session[:user_id]) %></li>
				              <li class="divider"></li>
				              <li><%= link_to 'Sign Out', signout_path %></li>
				            </ul>
							<% else %>
								<ul class="nav pull-right">
							    <li>
							    <div><%= link_to 'Login', signin_path, :class => "btn" %></div>
							    </li>
								</ul>
							  <% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Capital Tweet" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/edit.html.erb
<h3>Edit Profile</h3>
<h4><%= @user.name %></h4>

<br />
<%= form_for(@user) do |f| %>
  <%= f.error_messages %>
  <%= f.label :email %>
  <%= f.text_field :email, :value => current_user.email %>
  <br />
  <%= f.submit "Submit" %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>